import { InMemoryDbService } from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const imoveis = [
      { id: 240,  
        name: 'Apartamento em São Paulo, Jardim das Perdizes', 
        servicos: ['Lavanderia', 'Brinquedoteca', 'Salão gourmet', 'Vestiários', 'Piscina com raia', 'Piscina externa adulto', 'Salão de festas e gourmet', 'Sauna', 'Lounge com lareira', 'Churrasqueira gourmet',
        'Pergolado de relaxamento'],
        description: 'O Jardim das Perdizes fica ainda mais especial com o lançamento do mixed-use Time. O bairro planejado mais moderno de São Paulo agora traz o primeiro multiuso da cidade com torre residencial e parque integrado. Morar no Time é usufruir de todos os benefícios práticos, urbanos, tecnológicos de um dos bairros mais cobiçados e valorizados da atualidade.',
        dormitorios: 2,
        vagas: 4,
        img: "http://cdn.uso.com.br/248/2017/03/50016448.jpg",
        tipo: "compra"
      },
      { id: 231, 
        name: 'Apartamento em São Paulo, Jardim das Perdizes',
        servicos: ['Lavanderia', 'Brinquedoteca', 'Salão gourmet', 'Vestiários', 'Piscina com raia', 'Piscina externa adulto', 'Salão de festas e gourmet', 'Sauna', 'Lounge com lareira', 'Churrasqueira gourmet',
        'Pergolado de relaxamento'],
        description: 'O Bosque Araucária oferece apartamentos espaçosos, confortáveis e práticos, com várias opções de lazer. Localiza-se no Jardim das Perdizes, o novo bairro planejado de São Paulo, que garante qualidade de vida e conforto para toda sua família.',
        dormitorios: 4,
        vagas: 1,
        img: 'https://imagens.loopimoveis.com/d34e8d5743922517f5befc036035ad8a.jpeg',
        tipo: "aluguel"
      },
      { id: 228,
        name: "Apartamento em São Paulo, Jardim das Perdizes",
        servicos: [ 'Churrasqueira simples', 'Churrasqueira com forno de pizza', 'Espaço gourmet', 'Lounge de jogos', 'Atelier adolescente', 'Salão de festas adulto', 'Salão de festas adolescente', 'Salão de festas infantil', 'Quadra esportiva com apoio', 'Piscina adulto com biribol e deck molhado', 'Piscina adulto coberta, com raia de 25 metros', 'Solarium', 'Piscina infantil descoberta', 'Piscina infantil coberta', 'Sauna seca', 'Sauna úmida', 'Brinquedoteca para crianças menores', 'Brinquedoteca para crianças maiores', 'Cinema infantil', 'Playground com minipista', 'Sala de ginástica', 'Espaço yoga', 'Fitness', 'Espaço homem','Espaço mulher'],
        description: "Bosque Jequitibá é um exclusivo condomínio residencial de alto padrão com qualidade de vida em cada metro quadrado. Apartamentos com medidas amplas e mais de vinte itens de lazer, entre eles, o parque aquático com quatro piscinas.",
        dormitorios: 5,
        vagas: 4,
        img: "https://imagens.loopimoveis.com/3f7d7a8bf6cc6ecb745c6d5aae2db399.jpeg",
        tipo: "compra"
      },
      { id: 'AP3272-CRYS', 
        name: 'Apartamento em São Paulo, Brooklin',
        servicos: [],
        description: 'APARTAMENTO NOVO! PRONTO PARA MORAR FACHADA ESTILO CONTEPORANEO. 3 DORMITORIOS ( SENDO 1 SUITE) 2 VAGAS.SALA AMPLIANDA COM DOIS AMBIENTES E HOME OFFICE. HOME TEACHER COM LAVABO, SAUNA COM DUCHA E DESCANSO, PISCINA COBERTA AQUECIDA COM RAIA 25M, DECK DA PISCINA COM SPA, QUADRA, PLAYGROUNDS, PISTA DE SKATE. LAZER COMPLETO!!',
        dormitorios: 3,
        vagas: 2,
        img: "http://cdn1.valuegaia.com.br/_Fotos/16344/16986/D636EADAB65EA0661B067EAFF378624D3E9BEECF.jpg",
        tipo: "aluguel"
      },
      { id: 'AS43205-AD3', 
        name: 'Apartamento em São Paulo, Brooklin',
        servicos: [],
        description: 'APARTAMENTO NOVO! PRONTO PARA MORAR FACHADA ESTILO CONTEPORANEO. 3 DORMITORIOS ( SENDO 1 SUITE) 2 VAGAS.SALA AMPLIANDA COM DOIS AMBIENTES E HOME OFFICE. HOME TEACHER COM LAVABO, SAUNA COM DUCHA E DESCANSO, PISCINA COBERTA AQUECIDA COM RAIA 25M, DECK DA PISCINA COM SPA, QUADRA, PLAYGROUNDS, PISTA DE SKATE. LAZER COMPLETO!!',
        dormitorios: 3,
        vagas: 2,
        img: 'http://static.nidoimovel.com.br/18d8042386b79e2c279fd162df0205c8/imovel/AS/AS43205/AS43205001.jpg',
        tipo: "compra"
      },
      { id: 13, 
        name: 'Apartamento em São Paulo, Chácara Santo Antônio (zona Sul)',
        servicos: [],
        description: 'Belíssimo empreendimento na Chácara Santo Antônio, cercado de muito verde, e com todas as facilidades que a região oferece.Ótimo apartamento com 210m² de área útil com 4 dormitórios, sendo 3 suítes, closet, lavabo, sala para 3 ambientes integrada a varanda gourmet.Cozinha repleta de armários. Dependência de empregada com suíte. Lazer de clube, num raríssimo terreno com 19.000m², para sua família viver com conforto, requinte e tranquilidadeAgende sua visita.',
        dormitorios: 4,
        vagas: 4,
        img: 'https://imagens.loopimoveis.com/d82e2b528b383d5bc79f4cc2f009cbdd_loop.jpeg',
        tipo: "aluguel"
      },
      { id: 'CO0107-MSAI', 
        name: 'Apartamento em São Paulo, Vila Madalena',
        servicos: [],
        description: 'Cobertura duplex com localização privilegiada, a 500m do metrô Vila Madalena. Muita luz natural, espaços amplos e acolhedores, para morar bem!São 4 suítes, tendo a principal hidromassagem e varanda. Sala para 2 ambientes com lareira e varanda, sala de jantar, escritório, cozinha bem iluminada com móveis planejados Elgin, ótima área de serviço e dependência completa de funcionários. Repleta de armários para facilitar a organização.Deck externo com sauna úmida, piscina que pode ser reativada e atelier que pode ser revertido em churrasqueira. 3 vagas demarcadas e depósito privativo.Condomínio bem cuidado com piscina, churrasqueira, salão de festas e sauna.Entre em contato e saiba todos os detalhes sobre este ótimo imóvel!',
        dormitorios: 4,
        vagas: 3,
        img: 'https://imagens.loopimoveis.com/d82e2b528b383d5bc79f4cc2f009cbdd_loop.jpeg',
        tipo: "compra"
      },
      { id: 'AP1793-MSAI', 
        name: 'Apartamento em São Paulo, Vila Madalena',
        servicos: [],
        description: 'Ótima localização em local tranquilo e arborizado, próximo à Praça do Por do Sol. Apartamento pronto para morar com sala ampliada com lareira e terraço incorporado, sala de jantar, sala de almoço com área gourmet incorporada e sala íntima adaptada para escritório. 3 suítes, tendo a suíte máster terraço, closet e banheiro com pia dupla e banheira. 4 vagas de garagem e depósito privativo.',
        dormitorios: 4,
        vagas: 4,
        img: 'https://imagens.loopimoveis.com/386859d9704b2cc28d5542021d5b6320_loop.jpeg',
        tipo: "aluguel"
      },
      { id: 'AP17024-CAT', 
        name: 'Apartamento em São Paulo, água Rasa',
        servicos: [],
        description: 'Ótimo Apartamento muito bem localização; a 250 metros da Avenida Regente Feijó, 600 metros da Avenida Sapopemba e 800 metros do Shopping Anália Franco. São 89 m² distribuídos em 3 Dormitórios sendo 1 Suíte, Sala para 2 ambientes com sacada,/ Cozinha, Área de Serviço com dormitório de empregada com wc .// 2 Vagas Cobertas na Garagem. O Condomínio conta com completa estrutura de lazer, Salão de Jogos, Salão de Festas, Sauna, Play Ground, Piscina, Quadra Poliesportiva e Churrasqueira. Cercado com toda a infraestrutura de serviços e comércio que a região proporciona. Agende uma visita com seu Corretor.necessario fiador ou seguro fiança',
        dormitorios: 3,
        vagas: 2,
        img: 'https://imagens.loopimoveis.com/386859d9704b2cc28d5542021d5b6320_loop.jpeg',
        tipo: "compra"
      },
      { id: 'AP17024-CAT', 
        name: 'Apartamento em São Paulo, água Rasa',
        servicos: [],
        description: 'Excelente apartamento, próximo ao Jardim Anália Franco, Moderno e confortável ,60 metros de área útil, uma suíte, com armários,sala ampliada,terraço gourmet, piso em porcelanato , cozinha planejada, uma vaga de garagem, muito bem localizado, fácil acesso as principais vias, as melhores Escolas da região,Shopping, Hospitais e Clinicas, agende uma visita com nossos corretores.',
        dormitorios: 1,
        vagas: 1,
        img: 'https://imagens.loopimoveis.com/d63452cfdeee682484aeacade731cac8_loop.jpeg',
        tipo: "aluguel"
      },
      { id: 'AP3687-COS', 
        name: 'Apartamento em São Paulo, Vila Nova Conceição',
        servicos: [],
        description: 'Prédio de alto padrão a 1 quadra do Parque Ibirapuera.Excelente opção na Vila Nova Conceição, 2 suítes sendo 1 master com ar condicionado, 1 escritório e 3 vagas de garagem e depósito.Prédio com 8 andares tendo como lazer, piscina, quadra de squash.',
        dormitorios: 2,
        vagas: 3,
        img: 'https://imagens.loopimoveis.com/d63452cfdeee682484aeacade731cac8_loop.jpeg',
        tipo: "compra"
      }
    ];
    return { imoveis };
  }
}